# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ’Tpod’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'YYKit'
  pod 'SnapKit'
  pod 'QMUIKit'
  pod 'YetAnotherAnimationLibrary'
  pod 'WeexSDK'
  pod 'SDWebImage’
end

 
